global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  
  - job_name: rabbit-mq
    metrics_path: '/metrics'
    static_configs:
      - targets: ["rabbit-mq:15692"]
